language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  # Get Redis
  - git clone --depth=1 https://github.com/antirez/redis.git && cd redis && make && cd ..
  # Get ReJSON
  - git clone --depth=1 https://github.com/RedisLabsModules/ReJSON.git && cd ReJSON && make && cd ..
  # Install requirements
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install wheel
  - pip install twine
  # Install rejson-py to test rejson-py
  # - pip install -e .

before_script:
  - ./redis/src/redis-server --loadmodule ReJSON/src/rejson.so &

script:
  - coverage run --source=rejson setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "RedisLabs"
  password:
    secure: "gYsxZoUWtbxDNXtkn/m6m/9Xidoyi5bH46xLH5zx7+yDvde3rGplwU4zHU3reRUCWxot0ldCeQHXXIXDkTgRMDIK7cJel9GSR5as19s4soAz6aNskYMxTcowoqOynM8JUebCmDUCsj0nQi91xxfSaL3I9+ErzK+K9PKyQI12pqVKawcq0tZtT2nigOPbHV2+gqWmE+JqYBLQzIfB7dePeIoqqb8r9psMysx9MQqfOmZCVKEcUyxdivsVu8rgmVoJrM/1e7p89zOdyHHlpVyUqCtIi8Ywsli9vezj4+jyjx7sNzXvazrO40Ag9h0hhOhhcuFptHf4kp1WXxkWulqcV+9AetFHy+eBbaDLMOrCKyt0t7dePmlCnhpXQzn87TbebBQhhW+9vaWBXCEpD98UqlM1oo9VMJ3juPdlsLa8fC+ehhaxIwxjRNs6YRo6QmTPckJ+6IbRGUJh9Ml48X8AedG6xMA2aA8XpIx+uCeVnTlHsU1AzHLIAvIfK16tnEOFoDvqqHxLWIWNlreHeyEZlvGnwIpENpcNfmbN8A+LllUrDOcW0sQ0qbpIB8Nlb1ZXbOuuKN6/lBoSnUZBMkSp4j/KO3OxTmq5wiuAUAJmfavTzq7CZC2EGgHBl0SRoFty9u5N40uvApmo89zgSBBuy0KqSt5ekQqdoonfuy9gZmw="
  on:
    tags: true
